### ISSUE TITLE
display of fonts according to `hand` attribute does not work if `div` (on which `hand` is used) is interrupted by `pb`

### ISSUE THREAD

**Issue by timofruehwirth** [auden-in-austria-digital/aad-app#11]
see:
https://github.com/auden-in-austria-digital/aad-data/blob/1d76d9e1afc689292f19ff0bb922f761cf6c3506/data/xml/editions/aad-transcript__0037.xml#L182 

font is different displayed after `pb`:
https://auden-in-austria-digital.github.io/aad-app-dev/aad-transcript__0037.html?tab=2v&rev=on&ucl=on&gly=on&prs=on&plc=on&wrk=on&org=on&eve=on&nte=on&qte=on

is there anything I need to do on the data side?

**Comment by linxOD** [comment]
please test if it works

**Comment by timofruehwirth** [comment]
thank you, works perfectly now
