### ISSUE TITLE
display @hand values `^hand` and `^print`

### ISSUE THREAD

**Issue by timofruehwirth** [auden-in-austria-digital/aad-app#4]
wäre super - eigentlich ist die darstellung jetzt nicht wichtig, aber es wäre gutes feedback für mich, ob mein markup stimmt ...

**Comment by linxOD** [comment]
About #print_black_auden: https://github.com/auden-in-austria-digital/aad-data/blob/main/data/xml/editions/aad-transcript__0002.xml#L95

'sans-serif Grotesque-family typeface' is not a [Web Safe Font](https://www.w3schools.com/cssref/css_websafe_fonts.php). Meaning it is not supported by all Browsers or supported at all.
It is possible, however, to download fonts and add them to your CSS. But these fonts must be open and free to use. Google often provides free to use fonts but only if they are allowed to track your users. This would require a disclaimer.

**Comment by linxOD** [comment]
we already have fonts for typed, printed and handwritten. Currently in use: handwritten = Times New Roman for #hand_blue_auden and printed = Arial for #print_black_auden.

**Comment by timofruehwirth** [comment]
(1) but not yet displayed, right? as far as I can see, it's all Arial ...
(2) just for clarification: I have multiple values of @hand that start with "hand", including `hand_black_kurka_c` and various unidentified hands such as `hand_blue_unident_0010` (likewise, there will be multiple values starting with "print" as well as with "type")

**Comment by linxOD** [comment]
can you create a list of all hand values. I guess the values are usally the same print, hand and maybe a color?

**Comment by timofruehwirth** [comment]
aha - it works for the letter body, but not yet for the envelopes, where I use @hand on `<ab>`, e.g.,  https://github.com/auden-in-austria-digital/aad-data/blob/1ab25272b4cae21b47bbb46e67e8b61a7033e374/data/xml/editions/aad-transcript__0011.xml#L167

the list of @hand values is constantly expanding - my thought was whether you can work only with the beginning of the value: there are only three beginnings: `hand`, `type`, `print`. from my point of view, color needs not be represented, but different fonts will help me see whether I got the @hand values correct ...
